// <auto-generated />
using System;
using ConferenceRooms.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConferenceRooms.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ConferenceRoomsDbContext))]
    [Migration("20260828131024_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConferenceRooms.Core.Entities.Hall", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseHourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Halls", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BaseHourlyRate = 2000m,
                            Capacity = 50,
                            Name = "Hall A"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BaseHourlyRate = 3500m,
                            Capacity = 100,
                            Name = "Hall B"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BaseHourlyRate = 1500m,
                            Capacity = 30,
                            Name = "Hall C"
                        });
                });

            modelBuilder.Entity("ConferenceRooms.Core.Entities.ServiceOffering", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HallId")
                        .HasDatabaseName("IX_ServiceOfferings_HallId");

                    b.ToTable("ServiceOfferings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            HallId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Projector",
                            Price = 500m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            HallId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Wi-Fi",
                            Price = 300m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            HallId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Sound",
                            Price = 700m
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            HallId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Projector",
                            Price = 500m
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            HallId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Wi-Fi",
                            Price = 300m
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            HallId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Sound",
                            Price = 700m
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            HallId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Projector",
                            Price = 500m
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            HallId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Wi-Fi",
                            Price = 300m
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            HallId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Sound",
                            Price = 700m
                        });
                });

            modelBuilder.Entity("ConferenceRooms.Core.Entities.ServiceOffering", b =>
                {
                    b.HasOne("ConferenceRooms.Core.Entities.Hall", null)
                        .WithMany("ServiceOfferings")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConferenceRooms.Core.Entities.Hall", b =>
                {
                    b.Navigation("ServiceOfferings");
                });
#pragma warning restore 612, 618
        }
    }
}
